#!/usr/bin/env python
#coding=utf-8

#
# Copyright (C) 2014 - S. Zachariah Sprackett <zac@sprackett.com>
#

import sys
import os

sys.path.append(os.path.dirname(os.path.realpath(__file__)) + '/../')
from sensu_plugin import SensuPluginCheck


class ServiceCheck(SensuPluginCheck):
    def setup(self):
        self.parser.add_argument(
            '-o',
            '--ok',
            action="store_true"
        )
        self.parser.add_argument(
            '-w',
            '--warning',
            action="store_true"
        )
        self.parser.add_argument(
            '-c',
            '--critical',
            action="store_true"
        )
        self.parser.add_argument(
            '-u',
            '--unknown',
            action="store_true"
        )
        self.parser.add_argument(
            '-f',
            '--fail',
            action="store_true"
        )
        self.parser.add_argument(
            '-O',
            '--override',
            action="store_true"
        )

    def run(self):
        self.message("Testing, argv = %s" % " ".join(self.remain))
        if self.options.ok:
            self.ok()
        elif self.options.warning:
            self.warning()
        elif self.options.critical:
            self.critical()
        elif self.options.unknown:
            self.unknown()
        elif self.options.fail:
            raise RuntimeError
        elif self.options.override:
            self.ok("Overriding message")

if __name__ == "__main__":
    f = ServiceCheck()
