#!/usr/bin/env python
#coding=utf-8

#
# Copyright (C) 2014 - S. Zachariah Sprackett <zac@sprackett.com>
#

import sys
import os

sys.path.append(os.path.dirname(os.path.realpath(__file__)) + '/../')
from sensu_plugin import SensuPluginMetricStatsd


class TestMetric(SensuPluginMetricStatsd):
    def run(self):
        self.output('a', 1, 'ms')
        self.output('b.c.d', 15)
        self.ok()

if __name__ == "__main__":
    f = TestMetric()
